#!/bin/bash

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -credential)
    credential="$2"
    shift # past argument
    ;;
    -baseurl)
    baseurl="$2"
    shift # past argument
    ;;
    -username)
    username="$2"
    shift # past argument
    ;;
    *)
    shift        # unknown option
    ;;
esac

done

if [ -z ${credential+x} ]; then
  echo "-credential parameter must be set"
  exit 1
fi

if [ -z ${baseurl+x} ]; then
  echo "-baseurl parameter must be set"
  exit 1
fi


if [ -z ${username+x} ]; then
  echo "-username parameter must be set"
  exit 1
fi

echo apache2dummy
echo $credential $baseurl $username

if [ ! -d /var/www/html/wordpress/wp-content/themes/suffusion ]; then
    protocol="https"
    #protocol="http"

    wp --allow-root core install --path='/var/www/html/wordpress'  --title='test blog' --admin_user=$username --admin_password=$credential --admin_email='cityscope@ed.ac.uk' --url=$baseurl

    wp --allow-root plugin install wordpress-importer --activate
    wp --allow-root plugin install rest-api --activate
    wp --allow-root plugin install advanced-custom-fields --activate
    wp --allow-root plugin install wp-rest-api-v2-custom-fields --activate
    wp --allow-root plugin install osm --activate
    wp --allow-root plugin install wp-jquery-lightbox --activate
    wp --allow-root plugin install add-to-any --activate

    cp -r /tmp/resources/suffusion /var/www/html/wordpress/wp-content/themes/suffusion
    wp --allow-root theme activate suffusion

    sed -i -e "s@BASEURL@${protocol}://${baseurl}@g" /tmp/resources/sampletourblog.wordpress.xml

    wp --allow-root import /tmp/resources/sampletourblog.wordpress.xml --path='/var/www/html/wordpress' --authors='create'
    wp --allow-root option update blogname "$username Tour Blog"
    wp --allow-root option update blogdescription "A Guided Tour Blog Powered By Edinburgh Cityscope"
    wp --allow-root post delete 1 --force
    wp --allow-root option update permalink_structure "/%year%/%monthnum%/%day%/%postname%/"

    #convert base url to https
    wp --allow-root option update siteurl $protocol://$baseurl
    wp --allow-root option update home $protocol://$baseurl

    #TODO automate import of suffiosion settings

    #clear default widgets from sidebar

    wp --allow-root widget delete search-2
    wp --allow-root widget delete recent-posts-2
    wp --allow-root widget delete archives-2
    wp --allow-root widget delete categories-2
    wp --allow-root widget delete meta-2
    wp --allow-root widget delete recent-comments-2

    wp --allow-root widget add text  sidebar-1  --title="map" --text='[osm_map_v3 map_center="55.949, -3.195" zoom="12" width="100%" height="450" tagged_type="post" marker_name="mic_blue_pinother_2.png”]'
    wp --allow-root widget add a2a_follow_widget  sidebar-1  --title="Follow" --facebook_id="$username" --twitter_id="$username"

    wp --allow-root widget add text  sidebar-1  --title="link to app" --text="<a href=\"cityscope-tour://$baseurl/wordpress/$username?tour='My Tour'%26protocol='secure' \">App Launch URL</a>"
    wp --allow-root widget add text  sidebar-1  --title="mail app launch URL" --text="<a href=\"mailto:$username@ed.ac.uk?subject=cityscope tour launch url&body=cityscope-tour%3A%2F%2F$baseurl/wordpress/$username?tour='My Tour'%26protocol='secure' \">Send launch URL via email</a>"

    wp --allow-root media import /tmp/resources/RCS-museum.jpg --post_id=292 --title="Surgeons' Hall Museums" --featured_image
    wp --allow-root media import /tmp/resources/robert-knox-2.jpg --post_id=292 --title="Robert Knox"
    wp --allow-root media import /tmp/resources/surgeons-hall.jpg --post_id=292 --title="Surgeons' Hall"
    wp --allow-root media import /tmp/resources/old-college.jpg --post_id=287 --title="Old College" --featured_image
    wp --allow-root media import /tmp/resources/Apple_App_Store_Logo1.gif --post_id=655
    wp --allow-root media import /tmp/resources/PhoneSplash.png --post_id=655
    wp --allow-root media import /tmp/resources/PhoneMap.png --post_id=655
    wp --allow-root media import /tmp/resources/PhoneList.png --post_id=655

    #wp --allow-root option update  page_for_posts 565
    wp --allow-root option update show_on_front	page
    wp --allow-root option update  page_on_front 1199

    #wp --allow-root menu create "My Tour Menu"
    #wp --allow-root menu item add-post my-tour-menu 1199
    #wp --allow-root menu item add-post my-tour-menu 1182
    #wp --allow-root menu item add-post my-tour-menu 655
    wp --allow-root menu item add-post my-tour-menu 556
    wp --allow-root menu location assign my-tour-menu main

    #apt-get update

    echo "\$_SERVER['HTTP_HOST'] = \$_SERVER['HTTP_X_FORWARDED_HOST'];" >> wp-config.php
    echo "\$_SERVER['REQUEST_URI'] = '/wordpress/$username' . \$_SERVER['REQUEST_URI']; " >> wp-config.php
    echo "\$_SERVER['SCRIPT_NAME'] = '/wordpress/$username' . \$_SERVER['SCRIPT_NAME']; " >> wp-config.php
    echo "\$_SERVER['PHP_SELF'] = '/wordpress/$username' . \$_SERVER['PHP_SELF']; " >> wp-config.php
    echo "\$_SERVER['REMOTE_ADDR'] = \$_SERVER['HTTP_X_FORWARDED_FOR']; " >> wp-config.php
    echo "Updated wp-config.php"
    tail wp-config.php
else
    #If the container is restarting/recreated update the user's credential to ensure it's kept in sync with workbench
    wp --allow-root user update $username --user_pass=$credential
fi

apache2-foreground
